version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend
    volumes:
      - /usr/share/fonts/opentype/urw-base35/NimbusRoman-Regular.otf:/app/NimbusRoman-Regular.otf
    env_file:
      - .env
    ports:
      - "8000:8000"
  
  # frontend:
  #   build: ./frontend
  #   container_name: frontend
  #   ports:
  #     - "8050:8050"
  #   env_file:
  #     - .env
